name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake files
        uses: Platane/snk@v3
        with:
          github_user_name: aryanraj71
          outputs: |
            snake.svg
            snake-dark.svg?palette=github-dark
            snake.gif

      - name: Commit and push to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git rm -rf .
          cp snake.svg snake-dark.svg snake.gif .
          git add . 
          git commit -m "Update snake animation"
          git push --force origin output
